// Copyright 2020 The xxhash3 Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build !amd64

// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs defs.go

package xxhash3

const (
	sizeofPtr      = 0x8
	sizeofShort    = 0x2
	sizeofInt      = 0x4
	sizeofLong     = 0x8
	sizeofLongLong = 0x8
	sizeofSizeT    = 0x8
)

type (
	_C_short     int16
	_C_int       int32
	_C_long      int64
	_C_long_long int64
	_C_size_t    uint64
)

type M256 [8]float32
type M256d [4]float64
type M256i [4]int64
